{% set name = "herepy" %}
{% set version = "3.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/abdullahselek/HerePy/archive/{{ version }}.tar.gz
  sha256: f789ff947cb6a3b4222e38091d2cc4be8dbb3aec7a2f3d74b5ea28d917cf8e59

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - requests ==2.25

test:
  imports:
    - herepy

about:
  home: https://github.com/abdullahselek/HerePy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A library that provides a Python interface to the HERE APIs
  description: |
    A library that provides a Python interface to the HERE APIs
  doc_url: https://herepy.abdullahselek.com/
  dev_url: https://github.com/abdullahselek/HerePy

extra:
  recipe-maintainers:
    - abdullahselek
