{% set name = "herepy" %}
{% set version = "3.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 800b3cb28bc83c82187d82f02c56f8a80c10e6f32bf09eb591c5694afbadddf3
build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - requests ==2.25

test:
  imports:
    - herepy

about:
  home: https://github.com/abdullahselek/HerePy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A library that provides a Python interface to the HERE APIs
  description: |
    A library that provides a Python interface to the HERE APIs
  doc_url: https://herepy.abdullahselek.com/
  dev_url: https://github.com/abdullahselek/HerePy

extra:
  recipe-maintainers:
    - abdullahselek
