{% set name = "herepy" %}
{% set version = "3.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/abdullahselek/HerePy/archive/{{ version }}.tar.gz
  sha256: 6513b57a120d04b1db53f68feed19c030ace1133c311416fb334293ad63c7635

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - requests ==2.25

test:
  imports:
    - herepy

about:
  home: https://github.com/abdullahselek/HerePy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A library that provides a Python interface to the HERE APIs'
  description: |
    A library that provides a Python interface to the HERE APIs
  doc_url: https://herepy.abdullahselek.com/
  dev_url: https://github.com/abdullahselek/HerePy

extra:
  recipe-maintainers:
    - abdullahselek
